version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root_pass

  backend:
    build:
      context: /Users/msanteler/Sites/backend_ruby_service
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    volumes:
      - /Users/msanteler/Sites/backend_ruby_service:/app
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
    depends_on:
      - database
